import os
import re
from datetime import datetime

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT


def save_document(title: str, content: str):

    os.makedirs("output", exist_ok=True)

    # Clean filename
    filename = re.sub(r"[^a-zA-Z0-9 ]", "", title)
    filename = filename.strip().replace(" ", "_")

    if not filename:
        filename = "Generated_Document"

    # Prevent overwrite
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    filepath = os.path.join(
        "output",
        f"{filename}_{timestamp}.docx"
    )

    doc = Document()

    # -----------------------------
    # Title
    # -----------------------------
    title_para = doc.add_heading(level=0)
    title_para.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    run = title_para.add_run(title)
    run.font.size = Pt(22)
    run.bold = True

    doc.add_paragraph()

    # -----------------------------
    # Parse AI Output
    # -----------------------------
    for line in content.splitlines():

        line = line.strip()

        if not line:
            continue

        # Main Heading
        if line.startswith("# "):
            doc.add_heading(line.replace("# ", ""), level=1)

        # Section Heading
        elif line.startswith("## "):
            doc.add_heading(line.replace("## ", ""), level=2)

        # Bullet Points
        elif line.startswith("- "):
            doc.add_paragraph(
                line.replace("- ", ""),
                style="List Bullet"
            )

        elif line.startswith("* "):
            doc.add_paragraph(
                line.replace("* ", ""),
                style="List Bullet"
            )

        # Numbered list
        elif re.match(r"^\d+\.", line):
            doc.add_paragraph(
                line,
                style="List Number"
            )

        else:
            para = doc.add_paragraph(line)
            para.style.font.size = Pt(11)

    # Footer
    doc.add_page_break()

    footer = doc.sections[0].footer

    footer.paragraphs[0].text = (
        f"Generated by AutoDoc AI | "
        f"{datetime.now().strftime('%d %b %Y %I:%M %p')}"
    )

    doc.save(filepath)

    return filepath